ASFLAGS_ADDITIONAL = -mcpu=cortex-m0plus -mthumb -fno-exceptions
TARGET_LOAD_CMD = 
TARGET_LOAD_CMD_ARGS = 
TARGET_PKG_INSTALLDIR = C:/PROGRA~3/MATLAB/SUPPOR~1/R2020b/toolbox/target/SUPPOR~1/FREEDO~1
STACK_SIZE = 64
